import type { Metadata } from "next";
import "./globals.css";
import { ubuntu } from "./fonts/fonts";


export const metadata: Metadata = {
  title: "Max Camargo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className}`}>
        {children}
      </body>
    </html>
  );
}
